repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
        -   id: trailing-whitespace
  -   repo: https://github.com/psf/black
      rev: 19.3b0
      hooks:
        -   id: black
  -   repo: https://github.com/asottile/reorder_python_imports
      rev: v1.3.5
      hooks:
        -   id: reorder-python-imports
            language_version: python3
  -   repo: https://github.com/asottile/pyupgrade
      rev: v1.11.1
      hooks:
        -   id: pyupgrade